#Include "TopConn.CH"
#Include "Protheus.CH"
#Include "TOTVS.CH"
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัออออออออออออออออออออออออออปฑฑ
ฑฑบPrograma  PLFATE07    บAutor  ณWilson Junior	    				บDataณ19/05/2021   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯออออออออออออออออออออออออออนฑฑ
ฑฑบDesc.     ณ Verifica se existe produtos no deposito da loja							 ฑ
ฑฑบ          ณ                                                            			   บฑฑ
ฑฑฬออออออออออุอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ AP                                                        			   บฑฑ
ฑฑศออออออออออฯอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
user function VERIPRC(_cproduto)
	
	_nPreco := U_PLCOME01(_cproduto)


Return _nPreco

User Function PLCOME01(_cproduto)

	//Local aArea       := GetArea()
	Local cQuery      := ""

	Local nSaldo := 0
	//Fa็o a consulta para pegar as informa็๕es

cQuery := "	SELECT ISNULL(DA1_PRCVEN,'0') VENDA FROM DA1200 "
cQuery += " WHERE DA1_CODTAB = '003' "
cQuery += " AND DA1_CODPRO = '"+_cproduto+"' "	




	//Se o alias estiver aberto, irei fechar, isso ajuda a evitar erros
	If Select("TRBSE1") <> 0
		DbSelectArea("TRBSE1")
		TRBSE1->(DbCloseArea())
	EndIf

	//crio o novo alias
	TCQUERY cQuery NEW ALIAS "TRBSE1"

	dbSelectArea("TRBSE1")
	TRBSE1->(dbGoTop())

	nSaldo = TRBSE1->VENDA

Return (nSaldo)