DECLARE @RC int
DECLARE @FILIAIS varchar(2048)
DECLARE @DATAINI varchar(8)
DECLARE @DATAFIM varchar(8)
DECLARE @CFOP varchar(2048)
DECLARE @NCM varchar(10)
DECLARE @CONTAS varchar(20)
DECLARE @ITEMCC varchar(2048)
DECLARE @CLIFORDE varchar(6)
DECLARE @CLIFORATE varchar(6)
DECLARE @LOJADE varchar(2)
DECLARE @LOJAATE varchar(2)
DECLARE @ORDEM int

-- TODO: Set parameter values here.
SET @FILIAIS   = '02'
SET @DATAINI   = '20250101'
SET @DATAFIM   = '20250731'
SET @CFOP      = ''
SET @NCM       = ''
SET @CONTAS    = ''
SET @ITEMCC    = ''
SET @CLIFORDE  = ''
SET @CLIFORATE = 'ZZZZZZ'
SET @LOJADE    = ''
SET @LOJAATE   = 'ZZ'
SET @ORDEM     = '1'

EXECUTE @RC = [dbo].[SP_PLANILHA_FATURAMENTO_AUDITORIA_ANALITICO_SEL] 
   @FILIAIS
  ,@DATAINI
  ,@DATAFIM
  ,@CFOP
  ,@NCM
  ,@CONTAS
  ,@ITEMCC
  ,@CLIFORDE
  ,@CLIFORATE
  ,@LOJADE
  ,@LOJAATE
  ,@ORDEM
GO